// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class AccountConfig {
    /**
     * Creates a new AccountConfig instance.
     * @param {Partial<AccountConfig>} [$$source = {}] - The source object to create the AccountConfig.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AccountConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AccountConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AccountConfig(/** @type {Partial<AccountConfig>} */($$parsedSource));
    }
}

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("monitor" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["monitor"] = 0;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("opacity" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("refreshSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["refreshSeconds"] = 0;
        }
        if (!("barHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["barHeight"] = 0;
        }
        if (!("activeAccount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeAccount"] = 0;
        }
        if (!("accounts" in $$source)) {
            /**
             * @member
             * @type {AccountConfig[]}
             */
            this["accounts"] = [];
        }
        if (!("hotkeys" in $$source)) {
            /**
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkeys"] = (new HotkeyConfig());
        }
        if (!("startWithWindows" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["startWithWindows"] = false;
        }
        if (!("clickThrough" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clickThrough"] = false;
        }
        if (!("appBarMode" in $$source)) {
            /**
             * push apps down (AppBar API)
             * @member
             * @type {boolean}
             */
            this["appBarMode"] = false;
        }
        if (!("pinned" in $$source)) {
            /**
             * false = auto-hide on mouseleave, undocked
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("accounts" in $$parsedSource) {
            $$parsedSource["accounts"] = $$createField6_0($$parsedSource["accounts"]);
        }
        if ("hotkeys" in $$parsedSource) {
            $$parsedSource["hotkeys"] = $$createField7_0($$parsedSource["hotkeys"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("cycleMonitor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cycleMonitor"] = "";
        }
        if (!("toggleClickThrough" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toggleClickThrough"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = AccountConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = HotkeyConfig.createFrom;
