// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as claude$0 from "./internal/claude/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as terminal$0 from "./internal/terminal/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureAccounts() {
    return $Call.ByID(2903865439);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureStations() {
    return $Call.ByID(2270322734);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureTerminals() {
    return $Call.ByID(1237227572);
}

/**
 * DetectTerminal returns the auto-detected launcher for this machine without
 * persisting it — used by the editor to preselect a sensible default.
 * @returns {$CancellablePromise<config$0.LauncherConfig>}
 */
export function DetectTerminal() {
    return $Call.ByID(3295777970).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<claude$0.BarData | null>}
 */
export function GetBarData() {
    return $Call.ByID(1002198872).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<platform$0.MonitorInfo[]>}
 */
export function GetMonitors() {
    return $Call.ByID(3692271108).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPushdownStats returns active diagnostics for macOS window pushdown.
 * @returns {$CancellablePromise<platform$0.PushdownStats>}
 */
export function GetPushdownStats() {
    return $Call.ByID(2130621354).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * ListTerminalPresets returns the builtin terminal programs for this OS plus
 * the custom escape hatch, for the bar editor's dropdown.
 * @returns {$CancellablePromise<terminal$0.PresetInfo[]>}
 */
export function ListTerminalPresets() {
    return $Call.ByID(3249389343).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * OpenTerminal launches the configured launcher entry at index in a new,
 * visible terminal window. The launcher program is resolved lazily on first
 * use (no terminal detection happens in config.Defaults) and persisted.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function OpenTerminal(index) {
    return $Call.ByID(2247958725, index);
}

/**
 * ParseStationItem classifies a single URL/ID into a StationItem for the
 * stations editor (so URL parsing stays authoritative on the Go side).
 * @param {string} input
 * @returns {$CancellablePromise<config$0.StationItem>}
 */
export function ParseStationItem(input) {
    return $Call.ByID(1591082711, input).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * PickDirectory opens a native folder-picker and returns the chosen absolute
 * path, or "" if the user cancelled. The terminal editor uses this for the DIR
 * field — a browser file input can't yield a real OS path in WebView2.
 * @returns {$CancellablePromise<string>}
 */
export function PickDirectory() {
    return $Call.ByID(1347829059);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RadioPause() {
    return $Call.ByID(1036964326);
}

/**
 * RadioPlayStation starts (or resumes) the configured station at index. The
 * station player owns the queue, shuffle, auto-advance and looping; it drives
 * the single-track audio controller one track at a time.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function RadioPlayStation(index) {
    return $Call.ByID(1061425594, index);
}

/**
 * @param {number} v
 * @returns {$CancellablePromise<void>}
 */
export function RadioSetVolume(v) {
    return $Call.ByID(3673750934, v);
}

/**
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveAccount(index) {
    return $Call.ByID(4119675500, index);
}

/**
 * SetActiveStation persists which station is selected in the bar cycler. It
 * does not start playback (use RadioPlayStation for that).
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveStation(index) {
    return $Call.ByID(3286258115, index);
}

/**
 * SetEditorOpen forces the bar fully expanded while the inline accounts editor
 * is shown (the editor is launched from the tray with the cursor off-bar, and
 * must stay open until dismissed). On close, the hover-watcher re-evaluates
 * based on the current cursor position.
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetEditorOpen(open) {
    return $Call.ByID(3883131646, open);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetMonitor(index) {
    return $Call.ByID(2062485563, index);
}

/**
 * @param {number} opacity
 * @returns {$CancellablePromise<void>}
 */
export function SetOpacity(opacity) {
    return $Call.ByID(2521718736, opacity);
}

/**
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetPinned(pinned) {
    return $Call.ByID(721057701, pinned);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleClickThrough() {
    return $Call.ByID(2867525164);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleStartup() {
    return $Call.ByID(3862563746);
}

// Private type creation functions
const $$createType0 = config$0.LauncherConfig.createFrom;
const $$createType1 = claude$0.BarData.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.Config.createFrom;
const $$createType4 = platform$0.MonitorInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = platform$0.PushdownStats.createFrom;
const $$createType7 = terminal$0.PresetInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = config$0.StationItem.createFrom;
