// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as claude$0 from "./internal/claude/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "./internal/platform/models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ConfigureAccounts() {
    return $Call.ByID(2903865439);
}

/**
 * @returns {$CancellablePromise<claude$0.BarData | null>}
 */
export function GetBarData() {
    return $Call.ByID(1002198872).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<config$0.Config>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<platform$0.MonitorInfo[]>}
 */
export function GetMonitors() {
    return $Call.ByID(3692271108).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetPushdownStats returns active diagnostics for macOS window pushdown.
 * @returns {$CancellablePromise<platform$0.PushdownStats>}
 */
export function GetPushdownStats() {
    return $Call.ByID(2130621354).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetRadioStreamURL resolves the given YouTube livestream video ID to an HLS
 * manifest URL suitable for a top-level <audio> element. The frontend owns
 * the station list and passes the active video ID per call.
 * @param {string} videoID
 * @returns {$CancellablePromise<string>}
 */
export function GetRadioStreamURL(videoID) {
    return $Call.ByID(1255851915, videoID);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Quit() {
    return $Call.ByID(3181047470);
}

/**
 * RefreshRadioStreamURL forces a re-resolve, bypassing the cached URL for
 * the given video ID. Frontend should call this when hls.js or the <audio>
 * element fires a fatal error (signed URL may have expired or rotated).
 * @param {string} videoID
 * @returns {$CancellablePromise<string>}
 */
export function RefreshRadioStreamURL(videoID) {
    return $Call.ByID(3695927536, videoID);
}

/**
 * @param {config$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetActiveAccount(index) {
    return $Call.ByID(4119675500, index);
}

/**
 * SetEditorOpen forces the bar fully expanded while the inline accounts editor
 * is shown (the editor is launched from the tray with the cursor off-bar, and
 * must stay open until dismissed). On close, the hover-watcher re-evaluates
 * based on the current cursor position.
 * @param {boolean} open
 * @returns {$CancellablePromise<void>}
 */
export function SetEditorOpen(open) {
    return $Call.ByID(3883131646, open);
}

/**
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function SetMonitor(index) {
    return $Call.ByID(2062485563, index);
}

/**
 * @param {number} opacity
 * @returns {$CancellablePromise<void>}
 */
export function SetOpacity(opacity) {
    return $Call.ByID(2521718736, opacity);
}

/**
 * @param {boolean} pinned
 * @returns {$CancellablePromise<void>}
 */
export function SetPinned(pinned) {
    return $Call.ByID(721057701, pinned);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleClickThrough() {
    return $Call.ByID(2867525164);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ToggleStartup() {
    return $Call.ByID(3862563746);
}

// Private type creation functions
const $$createType0 = claude$0.BarData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = platform$0.MonitorInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = platform$0.PushdownStats.createFrom;
