// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBarData() {
  return window['go']['main']['App']['GetBarData']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMonitors() {
  return window['go']['main']['App']['GetMonitors']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetActiveAccount(arg1) {
  return window['go']['main']['App']['SetActiveAccount'](arg1);
}

export function SetMonitor(arg1) {
  return window['go']['main']['App']['SetMonitor'](arg1);
}

export function SetOpacity(arg1) {
  return window['go']['main']['App']['SetOpacity'](arg1);
}

export function ToggleClickThrough() {
  return window['go']['main']['App']['ToggleClickThrough']();
}
