// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {claude} from '../models';
import {config} from '../models';
import {platform} from '../models';

export function GetBarData():Promise<claude.BarData>;

export function GetConfig():Promise<config.Config>;

export function GetMonitors():Promise<Array<platform.MonitorInfo>>;

export function GetRadioStreamURL(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function RefreshRadioStreamURL(arg1:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SetActiveAccount(arg1:number):Promise<void>;

export function SetEditorOpen(arg1:boolean):Promise<void>;

export function SetMonitor(arg1:number):Promise<void>;

export function SetOpacity(arg1:number):Promise<void>;

export function SetPinned(arg1:boolean):Promise<void>;

export function ToggleClickThrough():Promise<boolean>;
